settings:
  min-players: 2
  max-players: 8
  cards-per-player: 7
  enable-special-cards: true

messages:
  game-start: "§aThe game has started!"
  game-end: "§eGame over! Winner: %player%"
  invalid-move: "§cYou can't play that card!"
  not-your-turn: "§cIt's not your turn!"
